### ISSUE TITLE
Image requests are redirected to lower quality cloudinary images

### ISSUE THREAD

**Issue by filfreire** [terales/socatar#76]
### I'm reporting a trouble encoutered in usage

When I visit socatar to get an image from twitter (https://socatar.com/twitter/filrfreire) or github (https://socatar.com/github/filfreire), I'm directed to the following page:

https://res.cloudinary.com/hah9f7pyw/image/fetch/s--zRkvprgx--/c_thumb,d_fallback.svg,f_auto,g_faces,h_100,w_100/https://twitter.com/filrfreire/profile_image%3Fsize%3Doriginal

And no longer get a higher resolution image with the current URL being socatar.

Screenshot:
![image](https://user-images.githubusercontent.com/11976836/35852346-917eb2ee-0b22-11e8-963a-307f0514ad8b.png)

/cc @terales

**Comment by terales** [comment]
Yep, there was default 100×100 image size introduced.  I'll add this to documentation.

@filfreire what is your usage pattern? Why do you need an original image?

**Comment by filfreire** [comment]
@terales I was used to use the links I posted in the issue in the browser and get the original images (in terms of size).

The URL also remained the same, and it didn't change to a cloudinary URL.

I'm sure the way it is now is good for people using the API, my issue is with browser usage.

**Comment by terales** [comment]
sorry, didn't get your point :(
What should be changed in the project, except the docs, from your point of view?

**Comment by filfreire** [comment]
@terales 
> Maybe, add special `original` size?
Yes, that would be a helpful feature. 

Apologies for not being clear, my point was: 
- by default, I wasn't getting the original image size;
- the URL, when we finish the request for the image, doesn't remain a simple socatar-domain URL, like `https://socatar.com/github/filfreire`, instead, it's a redirected URL `https://res.cloudinary.com/hah9f7pyw/image/fetch/s--IoQ95kFo--/c_thumb,d_fallback.svg,f_auto,g_faces,h_100,w_100/https://avatars2.githubusercontent.com/u/11976836%3Fv%3D4`

**Comment by terales** [comment]
Thanks! I've documented unclear behaviour and added `original` size
