### ISSUE TITLE
Not-found images don't scale

### ISSUE THREAD

**Issue by yegor256** [terales/socatar#92]
Try this one: https://socatar.com/facebook/user.is-absent/64-64

I expect it to be of 64x64 size. However, this is not the case.

**Comment by terales** [comment]
Thanks for the report! I'll fix this in two days

**Comment by terales** [comment]
Fixed: https://socatar.com/facebook/user.is-absent2/64-64

All other images would be updated in less than two weeks because of Cloudflare cache.
